name: Creating Event Trigger for Issues
on:
  issues:
    types: [opened, edited, reopened, closed]
  issue_comment:
    types: [created]
jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create issue comment
        run: |
          echo "Creating an issue comment..."
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue State: ${{ github.event.issue.state }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  comment_on_issue:
    if: github.event.issue.state == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print closing comment
        run: |
          echo "Closing comment: ${{ github.event.comment.body }}"
          echo "Closed by: ${{ github.event.comment.user.login }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}